name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # run-release:
  #   name: Run release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: Install Node.js dependencies
  #       run: npm ci

  #     - name: Package VS Code extension
  #       id: package
  #       uses: nhedger/package-vscode-extension@v1

  #     - name: "Get Previous tag"
  #       id: previoustag
  #       uses: "WyriHaximus/github-action-get-previous-tag@v1"

  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         body: ${{ steps.extract-release-notes.outputs.release_notes }}
  #         files: ${{ steps.package.outputs.packagePath }}
  #         tag_name: ${{ steps.previoustag.outputs.tag }}

  #     - name: Publish to Visual Studio Marketplace
  #       uses: HaaLeo/publish-vscode-extension@v1
  #       with:
  #         pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
  #         registryUrl: https://marketplace.visualstudio.com
